# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jkl < Formula
  desc "JKL is a version manager for other command-line tools. It installs tools quickly with minimal input, and helps you switch versions of tools while you work."
  homepage "https://github.com/ivanfetch/jkl"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivanfetch/jkl/releases/download/v0.0.8/jkl_0.0.8_darwin_amd64.tar.gz"
      sha256 "6a86ae0d1e0799fa335b9207d4baa8902b673cc1925cb069e2184bde007c3496"

      def install
        bin.install "jkl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivanfetch/jkl/releases/download/v0.0.8/jkl_0.0.8_darwin_arm64.tar.gz"
      sha256 "f15c514a7cf409e5b4350d091c19aea8634a3ca7f60ae7969b14578666f0a4b1"

      def install
        bin.install "jkl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivanfetch/jkl/releases/download/v0.0.8/jkl_0.0.8_linux_arm64.tar.gz"
      sha256 "c9d554409ea8994d7a653513d6111cd7e6a0b25b7e57adb49cf40f1cf29119be"

      def install
        bin.install "jkl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ivanfetch/jkl/releases/download/v0.0.8/jkl_0.0.8_linux_amd64.tar.gz"
      sha256 "1a452168e63f9cd6061b19820e1d9283192e6cae2fd48de9292feb23684aeaaf"

      def install
        bin.install "jkl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ivanfetch/jkl/releases/download/v0.0.8/jkl_0.0.8_linux_armv6.tar.gz"
      sha256 "0a6f2de988d134e1ecfa5995f261cf99f2fc1a9dbad82114fd7bac225ab5a357"

      def install
        bin.install "jkl"
      end
    end
  end

  def caveats; <<~EOS
    You will need to add the jkl shims directory (default ~/.jkl/bin) to your PATH.
  EOS
  end

  test do
    system "#{bin}/jkl version"
  end
end
