# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jkl < Formula
  desc "JKL is a version manager for other command-line tools. It installs tools quickly with minimal input, and helps you switch versions of tools while you work."
  homepage "https://github.com/ivanfetch/jkl"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivanfetch/jkl/releases/download/v0.0.4/jkl_0.0.4_darwin_amd64.tar.gz"
      sha256 "d02910b9a7bad6ea6b50b16a40830af1da770e74c63ac291301700100ef2fada"

      def install
        bin.install "jkl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivanfetch/jkl/releases/download/v0.0.4/jkl_0.0.4_darwin_arm64.tar.gz"
      sha256 "533fad6aa5157322a4e95a900572942444aebe900925103e5909c98c2513254e"

      def install
        bin.install "jkl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ivanfetch/jkl/releases/download/v0.0.4/jkl_0.0.4_linux_amd64.tar.gz"
      sha256 "b4c1e8f8bf2dc84a41509ce9b3c6962f40995b70692a553f94337454b7ae3448"

      def install
        bin.install "jkl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivanfetch/jkl/releases/download/v0.0.4/jkl_0.0.4_linux_arm64.tar.gz"
      sha256 "7c8098d8889b7ace575f3d079f6cc67b1b10fb57aec39fb3fafae86d07c680bf"

      def install
        bin.install "jkl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ivanfetch/jkl/releases/download/v0.0.4/jkl_0.0.4_linux_armv6.tar.gz"
      sha256 "d4613d2217845a1217cff13459f866856b7523541d49e8bb5a2063790b085301"

      def install
        bin.install "jkl"
      end
    end
  end

  def caveats; <<~EOS
    You will need to add the jkl shims directory (default ~/.jkl/bin) to your PATH.
  EOS
  end

  test do
    system "#{bin}/jkl version"
  end
end
